import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const dm = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Musssick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dm.className} overflow-x-hidden`}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
