import { DM_Sans } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import NavbarMain from "../components/Navbar";

const dm = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Musssick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dm.className} overflow-x-hidden`}>
        <NavbarMain />
        {children}
        <Footer />
      </body>
    </html>
  );
}
