import { DM_Sans } from "next/font/google";
import "./globals.css";
import ClientWrapper from "../components/ClientWrapper";
import { TicketProvider } from "../context/TicketContext";

const dm = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Musssick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dm.className} overflow-x-hidden`}>
        <TicketProvider>
          <ClientWrapper>{children}</ClientWrapper>
        </TicketProvider>
      </body>
    </html>
  );
}
