import { DM_Sans } from "next/font/google";
import Sidebar from "../../components/Sidebar";
const dm = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Musssick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dm.className} overflow-x-hidden`}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
